# Generated by Django 4.2.5 on 2023-09-17 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_choice_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='course',
            field=models.ForeignKey(default='online course', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
    ]
