# Generated by Django 4.2.5 on 2023-09-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_alter_choice_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
    ]
